# font configuration
font_family      JetBrainsMonoNL NF SemiBold
italic_font      JetBrainsMonoNL NF SemiBold Italic
bold_font        auto
bold_italic_font auto

font_size 13.0

# bell
enable_audio_bell no

# window size
remember_window_size  no
initial_window_width  80c
initial_window_height 25c

# window adding
window_padding_width 25
window_padding_height 30

# colors
cursor                #ffcc66
background            #041216
foreground            #c5c9c5
url_color             #0087BD
color0                #3B4252
color8                #4C566A
color1                #fb4934
color9                #fb4934
color2                #A3BE8C
color10               #A3BE8C
color3                #EBCB8B
color11               #EBCB8B
color4                #81A1C1
color12               #81A1C1
color5                #B48EAD
color13               #B48EAD
color6                #88C0D0
color14               #8FBCBB
color7                #E5E9F0
color15               #ECEFF4
