md: neovide
text/: neovide
text/html: firefox-dev
application/pdf: zathura
video/: mpv
image/: feh
audio/: mpv --audio-display=no
html: firefox-dev
ipynb: chromium
application/x-tar: alacritty
application/x-gzip: file-roller
application/x-bzip2: file-roller
application/x-rar: file-roller
application/x-xz: file-roller
application/zip: file-roller
inode/directory: alacritty -e lf
epub: zathura
djvu: zathura
